### ISSUE TITLE
TODO next version

### ISSUE THREAD

**Issue by Destroyer** [apocatarsis/Naga_KeypadMapper#18]
### install
- [x] fix "repeating installations" (writing multiple times to nagastart)
- [x] change owner of ~/.naga and ~/.profile to user (so they can change these without root privileges)
- [x] copy mapping_03.txt to ~/.naga as well

### docs
- [x] fix uninstallation info (.profile)
- [x] fix formatting

### executable
- [x] add docking station (to install script as well)
- [x] rename path variable in loadConf() to filename

**Comment by apocatarsis** [comment]
Very good ideas!. For the docking station, apparently the only thing that changes is an additional "_Dock-" in the device name, we could detect, in nagastart, if this appears in the naga device line and tell the naga exec with an additial input flag, something like "naga $version --dock=$IS_DOCKED", being $IS_DOCKED 0 or 1 for example.

**Comment by Destroyer** [comment]
@apocatarsis  I don't wanna to change your stuff testlab so I've forked the master and put my thoughts there. What do you think? It's still not finished 
https://github.com/apocatarsis/Naga_KeypadMapper/compare/master...Destroyer:master
